server:
  port: 9002
spring:
  application:
    name: ihrm-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    jpa:
      database: MySQL
      show-sql: true
      open-in-view: true
jwt:
  config:
    key: saas-ihrm
    ttl: 3600000